find . -name '*.json' -exec perl -i -pe 's/"items\//"item\//g' {} +
find . -name '*.json' -exec perl -i -pe 's/"blocks\//"block\//g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/apple_golden"/\/golden_apple"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/beef_cooked"/\/cooked_beef"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/beef_raw"/\/beef"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/book_enchanted"/\/enchanted_book"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/book_normal"/\/book"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/book_writable"/\/writable_book"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/book_written"/\/written_book"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/bow_standby"/\/bow"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/bucket_empty"/\/bucket"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/bucket_lava"/\/lava_bucket"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/bucket_milk"/\/milk_bucket"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/bucket_water"/\/water_bucket"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carrot_golden"/\/golden_carrot"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/chicken_cooked"/\/cooked_chicken"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/chicken_raw"/\/chicken"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_acacia"/\/acacia_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_birch"/\/birch_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_dark_oak"/\/dark_oak_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_iron"/\/iron_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_jungle"/\/jungle_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_spruce"/\/spruce_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_wood"/\/oak_door"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_black"/\/ink_sac"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_blue"/\/lapis_lazuli"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_brown"/\/cocoa_beans"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_cyan"/\/cyan_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_gray"/\/gray_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_green"/\/cactus_green"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_light_blue"/\/light_blue_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_lime"/\/lime_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_magenta"/\/magenta_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_orange"/\/orange_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_pink"/\/pink_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_purple"/\/purple_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_red"/\/rose_red"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_silver"/\/light_gray_dye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_white"/\/bone_meal"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dye_powder_yellow"/\/dandelion_yellow"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fireball"/\/fire_charge"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fireworks"/\/firework_rocket"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fireworks_charge"/\/firework_star"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fireworks_charge_overlay"/\/firework_star_overlay"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fish_clownfish_raw"/\/clownfish"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fish_cod_cooked"/\/cooked_cod"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fish_cod_raw"/\/cod"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fish_pufferfish_raw"/\/pufferfish"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fish_salmon_cooked"/\/cooked_salmon"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fish_salmon_raw"/\/salmon"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/fishing_rod_uncast"/\/fishing_rod"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_axe"/\/golden_axe"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_boots"/\/golden_boots"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_chestplate"/\/golden_chestplate"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_helmet"/\/golden_helmet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_hoe"/\/golden_hoe"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_horse_armor"/\/golden_horse_armor"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_leggings"/\/golden_leggings"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_pickaxe"/\/golden_pickaxe"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_shovel"/\/golden_shovel"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/gold_sword"/\/golden_sword"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/houstonia"/\/azure_bluet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/map_empty"/\/map"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/melon_speckled"/\/glistering_melon_slice"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/speckled_melon"/\/glistering_melon_slice"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/minecart_chest"/\/chest_minecart"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/minecart_command_block"/\/command_block_minecart"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/minecart_furnace"/\/furnace_minecart"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/minecart_hopper"/\/hopper_minecart"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/minecart_normal"/\/minecart"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/minecart_tnt"/\/tnt_minecart"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mutton_cooked"/\/cooked_mutton"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mutton_raw"/\/mutton"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/paeonia"/\/peony"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/porkchop_cooked"/\/cooked_porkchop"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/porkchop_raw"/\/porkchop"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potato_baked"/\/baked_potato"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potato_poisonous"/\/poisonous_potato"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potion_bottle_drinkable"/\/glass_bottle"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potion_bottle_empty"/\/potion"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potion_bottle_lingering"/\/lingering_potion"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potion_bottle_splash"/\/splash_potion"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rabbit_cooked"/\/cooked_rabbit"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rabbit_raw"/\/rabbit"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_11"/\/music_disc_11"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_13"/\/music_disc_13"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_blocks"/\/music_disc_blocks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_cat"/\/music_disc_cat"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_chirp"/\/music_disc_chirp"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_far"/\/music_disc_far"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_mall"/\/music_disc_mall"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_mellohi"/\/music_disc_mellohi"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_stal"/\/music_disc_stal"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_strad"/\/music_disc_strad"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_wait"/\/music_disc_wait"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/record_ward"/\/music_disc_ward"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/redstone_dust"/\/redstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/seeds_melon"/\/melon_seeds"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/seeds_pumpkin"/\/pumpkin_seeds"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/seeds_wheat"/\/wheat_seeds"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/slimeball"/\/slime_ball"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/spider_eye_fermented"/\/fermented_spider_eye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/totem"/\/totem_of_undying"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_axe"/\/wooden_axe"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_hoe"/\/wooden_hoe"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_pickaxe"/\/wooden_pickaxe"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_shovel"/\/wooden_shovel"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_sword"/\/wooden_sword"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wooden_armorstand"/\/armor_stand"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wooden_pressure_plate"/\/oak_pressure_plate"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_pressure_plate"/\/oak_pressure_plate"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/trip_wire"/\/tripwire"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/anvil_base"/\/anvil"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/anvil_slightly_damaged"/\/chipped_anvil"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/anvil_top_damaged_0"/\/anvil_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/anvil_top_damaged_1"/\/chipped_anvil_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/anvil_top_damaged_2"/\/damaged_anvil_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/anvil_very_damaged"/\/damaged_anvil"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/beetroots_stage_0"/\/beetroots_stage0"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/beetroots_stage_1"/\/beetroots_stage1"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/beetroots_stage_2"/\/beetroots_stage2"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/beetroots_stage_3"/\/beetroots_stage3"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/brick"/\/bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carrots_stage_0"/\/carrots_stage0"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carrots_stage_1"/\/carrots_stage1"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carrots_stage_2"/\/carrots_stage2"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carrots_stage_3"/\/carrots_stage3"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/cobblestone_mossy"/\/mossy_cobblestone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/cocoa_stage_0"/\/cocoa_stage0"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/cocoa_stage_1"/\/cocoa_stage1"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/cocoa_stage_2"/\/cocoa_stage2"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/comparator_off"/\/comparator"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_light_blue"/\/light_blue_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_black"/\/black_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_blue"/\/blue_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_brown"/\/brown_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_cyan"/\/cyan_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_gray"/\/gray_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_green"/\/green_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_lime"/\/lime_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_magenta"/\/magenta_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_orange"/\/orange_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_pink"/\/pink_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_black"/\/black_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_blue"/\/blue_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_brown"/\/brown_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_cyan"/\/cyan_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_gray"/\/gray_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_green"/\/green_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_light_blue"/\/light_blue_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_lime"/\/lime_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_magenta"/\/magenta_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_orange"/\/orange_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_pink"/\/pink_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_purple"/\/purple_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_red"/\/red_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_silver"/\/light_gray_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_white"/\/white_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_powder_yellow"/\/yellow_concrete_powder"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_purple"/\/purple_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_red"/\/red_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_silver"/\/light_gray_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_white"/\/white_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/concrete_yellow"/\/yellow_concrete"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/deadbush"/\/dead_bush"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dirt_podzol_side"/\/podzol_side"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dirt_podzol_top"/\/podzol_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dispenser_front_horizontal"/\/dispenser_front"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_acacia_lower"/\/acacia_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/acacia_door_lower"/\/acacia_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_acacia_upper"/\/acacia_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/acacia_door_upper"/\/acacia_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_birch_lower"/\/birch_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/birch_door_lower"/\/birch_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_birch_upper"/\/birch_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/birch_door_upper"/\/birch_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_dark_oak_lower"/\/dark_oak_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dark_oak_door_lower"/\/dark_oak_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_dark_oak_upper"/\/dark_oak_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dark_oak_door_upper"/\/dark_oak_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_iron_lower"/\/iron_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/iron_door_lower"/\/iron_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_iron_upper"/\/iron_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/iron_door_upper"/\/iron_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_jungle_lower"/\/jungle_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/jungle_door_lower"/\/jungle_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_jungle_upper"/\/jungle_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/jungle_door_upper"/\/jungle_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_spruce_lower"/\/spruce_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/spruce_door_lower"/\/spruce_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_spruce_upper"/\/spruce_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/spruce_door_upper"/\/spruce_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_wood_lower"/\/oak_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/oak_door_lower"/\/oak_door_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/door_wood_upper"/\/oak_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/oak_door_upper"/\/oak_door_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_fern_bottom"/\/large_fern_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_fern_top"/\/large_fern_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_grass_bottom"/\/tall_grass_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_grass_top"/\/tall_grass_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_paeonia_bottom"/\/peony_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_paeonia_top"/\/peony_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_rose_bottom"/\/rose_bush_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_rose_top"/\/rose_bush_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_sunflower_back"/\/sunflower_back"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_sunflower_bottom"/\/sunflower_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_sunflower_front"/\/sunflower_front"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_sunflower_top"/\/sunflower_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_syringa_bottom"/\/lilac_bottom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/double_plant_syringa_top"/\/lilac_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/dropper_front_horizontal"/\/dropper_front"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/enchanting_table_base"/\/enchanting_table"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/end_bricks"/\/end_stone_bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/end_portal_frame_empty"/\/end_portal_frame"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/endframe_eye"/\/end_portal_frame_eye"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/endframe_side"/\/end_portal_frame_side"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/endframe_top"/\/end_portal_frame_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/farmland_dry"/\/farmland"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/farmland_wet"/\/farmland_moist"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_allium"/\/allium"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_blue_orchid"/\/blue_orchid"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_dandelion"/\/dandelion"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_houstonia"/\/azure_bluet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_oxeye_daisy"/\/oxeye_daisy"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_rose"/\/poppy"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_tulip_orange"/\/orange_tulip"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_tulip_pink"/\/pink_tulip"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_tulip_red"/\/red_tulip"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/flower_tulip_white"/\/white_tulip"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/furnace_front_off"/\/furnace_front"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_black"/\/black_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_blue"/\/blue_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_brown"/\/brown_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_cyan"/\/cyan_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_gray"/\/gray_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_green"/\/green_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_light_blue"/\/light_blue_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_lime"/\/lime_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_magenta"/\/magenta_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_orange"/\/orange_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pink"/\/pink_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_purple"/\/purple_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_red"/\/red_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_silver"/\/light_gray_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_white"/\/white_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_yellow"/\/yellow_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_black"/\/black_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_blue"/\/blue_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_brown"/\/brown_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_cyan"/\/cyan_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_gray"/\/gray_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_green"/\/green_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_light_blue"/\/light_blue_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_lime"/\/lime_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_magenta"/\/magenta_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_orange"/\/orange_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_pink"/\/pink_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_purple"/\/purple_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_red"/\/red_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_silver"/\/light_gray_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_white"/\/white_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glass_pane_top_yellow"/\/yellow_stained_glass_pane_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_black"/\/black_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_blue"/\/blue_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_brown"/\/brown_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_cyan"/\/cyan_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_gray"/\/gray_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_green"/\/green_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_light_blue"/\/light_blue_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_lime"/\/lime_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_magenta"/\/magenta_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_orange"/\/orange_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_pink"/\/pink_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_purple"/\/purple_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_red"/\/red_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_silver"/\/light_gray_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_white"/\/white_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/glazed_terracotta_yellow"/\/yellow_glazed_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/grass_side"/\/grass_block_side"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/grass_side_overlay"/\/grass_block_side_overlay"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/grass_side_snowed"/\/grass_block_snow"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/grass_top"/\/grass_block_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay"/\/terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_black"/\/black_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_blue"/\/blue_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_brown"/\/brown_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_cyan"/\/cyan_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_gray"/\/gray_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_green"/\/green_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_light_blue"/\/light_blue_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_lime"/\/lime_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_magenta"/\/magenta_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_orange"/\/orange_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_pink"/\/pink_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_red"/\/red_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_silver"/\/light_gray_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_white"/\/white_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hardened_clay_stained_yellow"/\/yellow_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/ice_packed"/\/packed_ice"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/leaves_acacia"/\/acacia_leaves"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/leaves_big_oak"/\/dark_oak_leaves"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/leaves_birch"/\/birch_leaves"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/leaves_jungle"/\/jungle_leaves"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/leaves_oak"/\/oak_leaves"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/leaves_spruce"/\/spruce_leaves"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_acacia"/\/acacia_log"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_acacia_top"/\/acacia_log_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_big_oak"/\/dark_oak_log"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_big_oak_top"/\/dark_oak_log_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_birch"/\/birch_log"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_birch_top"/\/birch_log_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_jungle"/\/jungle_log"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_jungle_top"/\/jungle_log_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_oak"/\/oak_log"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_oak_top"/\/oak_log_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_spruce"/\/spruce_log"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/log_spruce_top"/\/spruce_log_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/melon_stem_connected"/\/attached_melon_stem"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/melon_stem_disconnected"/\/melon_stem"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mushroom_block_skin_brown"/\/brown_mushroom_block"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mushroom_block_skin_red"/\/red_mushroom_block"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mushroom_block_skin_stem"/\/mushroom_stem"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mushroom_brown"/\/brown_mushroom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/mushroom_red"/\/red_mushroom"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/nether_brick"/\/nether_bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/nether_wart_stage_0"/\/nether_wart_stage0"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/nether_wart_stage_1"/\/nether_wart_stage1"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/nether_wart_stage_2"/\/nether_wart_stage2"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/noteblock"/\/note_block"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/observer_back_lit"/\/observer_back_on"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/piston_inventory_normal"/\/piston_inventory"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/piston_inventory_sticky"/\/sticky_piston_inventory"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/piston_normal"/\/piston"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/piston_top_normal"/\/piston_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/planks_acacia"/\/acacia_planks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/planks_big_oak"/\/dark_oak_planks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/planks_birch"/\/birch_planks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/planks_jungle"/\/jungle_planks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/planks_oak"/\/oak_planks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/planks_spruce"/\/spruce_planks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potatoes_stage_0"/\/potatoes_stage0"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potatoes_stage_1"/\/potatoes_stage1"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potatoes_stage_2"/\/potatoes_stage2"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/potatoes_stage_3"/\/potatoes_stage3"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/prismarine_dark"/\/dark_prismarine"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/prismarine_rough"/\/prismarine"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/prismarine_rough.mcmeta/prismarine.mcmeta/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/pumpkin_face_off"/\/pumpkin_face"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/pumpkin_stem_connected"/\/attached_pumpkin_stem"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/pumpkin_stem_disconnected"/\/pumpkin_stem"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/purple_stained_glass"/\/purple_stained_glass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/purpur_pillar"/\/purpur_pillar"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/purpur_pillar_top"/\/purpur_pillar_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/quartz_block_chiseled"/\/chiseled_quartz_block"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/quartz_block_chiseled_top"/\/chiseled_quartz_block_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/quartz_block_lines"/\/quartz_pillar"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/quartz_block_lines_top"/\/quartz_pillar_top"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/quartz_ore"/\/nether_quartz_ore"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_activator"/\/activator_rail"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_activator_powered"/\/activator_rail_on"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_detector"/\/detector_rail"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_detector_powered"/\/detector_rail_on"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_golden"/\/powered_rail"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_golden_powered"/\/powered_rail_on"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_normal"/\/rail"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/rail_normal_turned"/\/rail_corner"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/red_sandstone_carved"/\/chiseled_red_sandstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/red_sandstone_normal"/\/red_sandstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/red_sandstone_smooth"/\/cut_red_sandstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/redstone_torch_on"/\/redstone_torch"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/reeds"/\/sugar_cane"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/repeater_off"/\/repeater"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sandstone_carved"/\/chiseled_sandstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sandstone_normal"/\/sandstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sandstone_smooth"/\/cut_sandstone"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sapling_acacia"/\/acacia_sapling"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sapling_birch"/\/birch_sapling"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sapling_jungle"/\/jungle_sapling"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sapling_oak"/\/oak_sapling"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sapling_roofed_oak"/\/dark_oak_sapling"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sapling_spruce"/\/spruce_sapling"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/slime"/\/slime_block"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/sponge_wet"/\/wet_sponge"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stone_andesite"/\/andesite"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stone_andesite_smooth"/\/polished_andesite"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stone_diorite"/\/diorite"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stone_diorite_smooth"/\/polished_diorite"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stone_granite"/\/granite"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stone_granite_smooth"/\/polished_granite"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stonebrick"/\/stone_bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stonebrick_carved"/\/chiseled_stone_bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stonebrick_cracked"/\/cracked_stone_bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/stonebrick_mossy"/\/mossy_stone_bricks"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/tallgrass"/\/grass"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/terracotta_purple"/\/purple_terracotta"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/torch_on"/\/torch"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/trip_wire_source"/\/trip_wire_hook"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/waterlily"/\/lily_pad"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/web"/\/cobweb"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_0"/\/wheat_stage0"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_1"/\/wheat_stage1"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_2"/\/wheat_stage2"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_3"/\/wheat_stage3"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_4"/\/wheat_stage4"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_5"/\/wheat_stage5"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_6"/\/wheat_stage6"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wheat_stage_7"/\/wheat_stage7"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_black"/\/black_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_blue"/\/blue_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_brown"/\/brown_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_cyan"/\/cyan_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_gray"/\/gray_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_green"/\/green_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_light_blue"/\/light_blue_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_lime"/\/lime_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_magenta"/\/magenta_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_orange"/\/orange_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_pink"/\/pink_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_purple"/\/purple_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_red"/\/red_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_silver"/\/light_gray_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_white"/\/white_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wool_colored_yellow"/\/yellow_wool"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_black"/\/black_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_blue"/\/blue_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_brown"/\/brown_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_cyan"/\/cyan_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_green"/\/green_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_light_blue"/\/light_blue_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_lime"/\/lime_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_magenta"/\/magenta_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_orange"/\/orange_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_pink"/\/pink_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_purple"/\/purple_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_red"/\/red_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_silver"/\/light_gray_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/silver_carpet"/\/light_gray_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_white"/\/white_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_yellow"/\/yellow_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/carpet_gray"/\/gray_carpet"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wooden_pressure_plate"/\/oak_pressure_plate"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/wood_pressure_plate"/\/oak_pressure_plate"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/trapdoor"/\/oak_trapdoor"/g' {} +
find . -name '*.json' -exec perl -i -pe 's/\/hopper_down"/\/hoppe"/g' {} +
